name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install qemu-user-static
        run: |
          cd /tmp
          wget -q -O qemu-user-static.deb http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_7.1+dfsg-2+b1_amd64.deb
          sudo apt install ./qemu-user-static.deb
          rm ./qemu-user-static.deb
          qemu-riscv64-static --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          # Make the image available in next step
          load: true
          platforms: linux/riscv64
          tags: ghcr.io/codewars/riscv:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run multiply example
        run: bin/run multiply

      - name: Run multiply-failing example
        run: bin/run multiply-failing || true

      - name: Run syntax-error example
        run: bin/run syntax-error || true

      - name: Run invalid-regname example
        run: bin/run invalid-regname || true

      - name: Run rvv-memcpy example
        run: bin/run rvv-memcpy

      - name: Run rvk-sha256sig0 example
        run: bin/run rvk-sha256sig0
